// src/app/question-card/question-card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Question, QuestionStatus, Category } from '../types';
import { CharCodePipe } from '../char-code-pipe';

@Component({
  selector: 'app-question-card',
  standalone: true,
  imports: [CharCodePipe],
  templateUrl: './question-card.component.html',
  styleUrls: ['./question-card.component.css'],
})
export class QuestionCardComponent {
  @Input() data!: Question;
  @Input() category!: Category;
  @Input() status: QuestionStatus | undefined;
  @Output() select = new EventEmitter<{ questionId: number; optionIndex: number }>();
  @Output() toggleBookmark = new EventEmitter<number>();

  get isAnswered(): boolean {
    return this.status?.selectedOption !== undefined && this.status.selectedOption !== null;
  }

  get isBookmarked(): boolean {
    return this.status?.isBookmarked || false;
  }

  onSelect(questionId: number, optionIndex: number): void {
    this.select.emit({ questionId, optionIndex });
  }

  onToggleBookmark(questionId: number): void {
    this.toggleBookmark.emit(questionId);
  }
}

<div id="q-{{ data.id }}" class="group bg-white border border-slate-200 rounded-xl shadow-sm hover:shadow-md transition-all duration-200 overflow-hidden">
      
  <!-- Header / Meta -->
  <div class="bg-slate-50/50 px-6 py-4 border-b border-slate-100 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <span class="text-xs font-mono font-bold text-slate-400">#{{ data.id.toString().padStart(3, '0') }}</span>
      <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium border"
        [ngClass]="{
          'bg-purple-50 text-purple-700 border-purple-100': category === 'Architecture',
          'bg-blue-50 text-blue-700 border-blue-100': category === 'Memory',
          'bg-orange-50 text-orange-700 border-orange-100': category === 'Protocols',
          'bg-rose-50 text-rose-700 border-rose-100': category === 'Real-Time',
          'bg-slate-100 text-slate-600 border-slate-200': true
        }">
        {{ category }}
      </span>
    </div>
    <button 
      (click)="onToggleBookmark(data.id)"
      class="focus:outline-none transition-colors duration-200"
      [ngClass]="{'text-amber-400': isBookmarked, 'text-slate-300 hover:text-amber-400': !isBookmarked}"
      title="Bookmark for review"
    >
      <svg class="w-5 h-5" [attr.fill]="isBookmarked ? 'currentColor' : 'none'" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
      </svg>
    </button>
  </div>

  <!-- Content -->
  <div class="p-6">
    <h3 class="text-lg font-medium text-slate-900 leading-relaxed mb-6">
      {{ data.question }}
    </h3>

    <div class="grid grid-cols-1 gap-3">
      <button
        *ngFor="let option of data.options; let i = index"
        [disabled]="isAnswered"
        (click)="onSelect(data.id, i)"
        class="relative w-full text-left px-4 py-3 rounded-lg border transition-all duration-200 flex items-start"
        [ngClass]="{
          'border-slate-200 hover:border-indigo-300 hover:bg-slate-50': !isAnswered,
          'bg-emerald-50/50 border-emerald-500 shadow-sm ring-1 ring-emerald-500/20': isAnswered && i === data.correctAnswer,
          'bg-rose-50/50 border-rose-500': isAnswered && i === status?.selectedOption && i !== data.correctAnswer,
          'bg-slate-50 border-slate-100 opacity-50 grayscale': isAnswered && i !== data.correctAnswer && i !== status?.selectedOption
        }"
      >
        <span class="flex-shrink-0 w-5 h-5 rounded-full border mr-3 flex items-center justify-center text-[10px] mt-0.5"
          [ngClass]="{
            'border-slate-300 text-slate-400': !isAnswered,
            'border-emerald-500 bg-emerald-500 text-white': isAnswered && i === data.correctAnswer,
            'border-rose-500 bg-rose-500 text-white': isAnswered && i === status?.selectedOption && i !== data.correctAnswer,
            'border-slate-200 text-slate-300': isAnswered && i !== data.correctAnswer && i !== status?.selectedOption
          }"
        >
          {{ (65 + i) | charCode }}
        </span>
        <span class="text-sm"
          [ngClass]="{
            'text-slate-700': !isAnswered,
            'text-emerald-900 font-medium': isAnswered && i === data.correctAnswer,
            'text-rose-900': isAnswered && i === status?.selectedOption && i !== data.correctAnswer,
            'text-slate-500': isAnswered && i !== data.correctAnswer && i !== status?.selectedOption
          }"
        >{{ option }}</span>
      </button>
    </div>
    
    <div *ngIf="isAnswered && !status?.isCorrect" class="mt-5 text-sm flex items-center gap-2 text-slate-500 bg-slate-50 py-2 px-3 rounded border border-slate-100">
      <svg class="w-4 h-4 text-emerald-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span>Correct Answer: <span class="font-semibold text-slate-700">{{ (65 + data.correctAnswer) | charCode }}</span></span>
    </div>
</div>

// components/QuestionCard.tsx
import React from 'react';
import { Question, QuestionStatus, Category } from '../types';

interface Props {
  data: Question;
  category: Category;
  status: QuestionStatus | undefined;
  onSelect: (questionId: number, optionIndex: number) => void;
  onToggleBookmark: (questionId: number) => void;
}

export const QuestionCard: React.FC<Props> = ({ data, category, status, onSelect, onToggleBookmark }) => {
  const isAnswered = status?.selectedOption !== undefined && status.selectedOption !== null;
  const isBookmarked = status?.isBookmarked || false;

  return (
    <div id={`q-${data.id}`} className="group bg-white border border-slate-200 rounded-xl shadow-sm hover:shadow-md transition-all duration-200 overflow-hidden">
      
      {/* Header / Meta */}
      <div className="bg-slate-50/50 px-6 py-4 border-b border-slate-100 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <span className="text-xs font-mono font-bold text-slate-400">#{data.id.toString().padStart(3, '0')}</span>
          <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium border ${
            category === 'Architecture' ? 'bg-purple-50 text-purple-700 border-purple-100' :
            category === 'Memory' ? 'bg-blue-50 text-blue-700 border-blue-100' :
            category === 'Protocols' ? 'bg-orange-50 text-orange-700 border-orange-100' :
            category === 'Real-Time' ? 'bg-rose-50 text-rose-700 border-rose-100' :
            'bg-slate-100 text-slate-600 border-slate-200'
          }`}>
            {category}
          </span>
        </div>
        <button 
          onClick={(e) => { e.stopPropagation(); onToggleBookmark(data.id); }}
          className={`focus:outline-none transition-colors duration-200 ${isBookmarked ? 'text-amber-400' : 'text-slate-300 hover:text-amber-400'}`}
          title="Bookmark for review"
        >
          <svg className="w-5 h-5" fill={isBookmarked ? "currentColor" : "none"} stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
          </svg>
        </button>
      </div>

      {/* Content */}
      <div className="p-6">
        <h3 className="text-lg font-medium text-slate-900 leading-relaxed mb-6">
          {data.question}
        </h3>

        <div className="grid grid-cols-1 gap-3">
          {data.options.map((option, index) => {
            let containerClass = "relative w-full text-left px-4 py-3 rounded-lg border transition-all duration-200 flex items-start ";
            let textClass = "text-sm ";
            let indicatorClass = "flex-shrink-0 w-5 h-5 rounded-full border mr-3 flex items-center justify-center text-[10px] mt-0.5 ";

            if (!isAnswered) {
              containerClass += "border-slate-200 hover:border-indigo-300 hover:bg-slate-50";
              textClass += "text-slate-700";
              indicatorClass += "border-slate-300 text-slate-400";
            } else {
              if (index === data.correctAnswer) {
                containerClass += "bg-emerald-50/50 border-emerald-500 shadow-sm ring-1 ring-emerald-500/20";
                textClass += "text-emerald-900 font-medium";
                indicatorClass += "border-emerald-500 bg-emerald-500 text-white";
              } else if (index === status.selectedOption) {
                containerClass += "bg-rose-50/50 border-rose-500";
                textClass += "text-rose-900";
                indicatorClass += "border-rose-500 bg-rose-500 text-white";
              } else {
                containerClass += "bg-slate-50 border-slate-100 opacity-50 grayscale";
                textClass += "text-slate-500";
                indicatorClass += "border-slate-200 text-slate-300";
              }
            }

            return (
              <button
                key={index}
                disabled={isAnswered}
                onClick={() => onSelect(data.id, index)}
                className={containerClass}
              >
                <span className={indicatorClass}>
                  {String.fromCharCode(65 + index)}
                </span>
                <span className={textClass}>{option}</span>
              </button>
            );
          })}
        </div>
        
        {isAnswered && !status.isCorrect && (
          <div className="mt-5 text-sm flex items-center gap-2 text-slate-500 bg-slate-50 py-2 px-3 rounded border border-slate-100">
            <svg className="w-4 h-4 text-emerald-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <span>Correct Answer: <span className="font-semibold text-slate-700">{String.fromCharCode(65 + data.correctAnswer)}</span></span>
          </div>
        )}
      </div>
    </div>
  );
};
